force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Communication__c.field-meta.xml
<CustomField>
    <fullName>Role_Communication__c</fullName>
    <label>Role Communication</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Description__c.field-meta.xml
<CustomField>
    <fullName>Role_Description__c</fullName>
    <label>Role Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Functionalknowledge__c.field-meta.xml
<CustomField>
    <fullName>Role_Functionalknowledge__c</fullName>
    <label>Role Functionalknowledge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_MentoringRequiered__c.field-meta.xml
<CustomField>
    <fullName>Role_MentoringRequiered__c</fullName>
    <label>Role MentoringRequiered</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Role_Prerequisites__c</fullName>
    <label>Role Prerequisites</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Softskills__c.field-meta.xml
<CustomField>
    <fullName>Role_Softskills__c</fullName>
    <label>Role Softskills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Role_Technicalknowledge__c.field-meta.xml
<CustomField>
    <fullName>Role_Technicalknowledge__c</fullName>
    <label>Role Technicalknowledge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LWCEmployeeRoleController.cls
public class  LWCEmployeeRoleController {

    @AuraEnabled (cacheable=true)
    public static Salesforce_Career_Path_Settings__mdt getRoleInformation(String empId){
        Salesforce_Career_Path_Settings__mdt roleDesc;
        List<Salesforce_Career_Path_Settings__mdt> lstroleDesc = [SELECT 
                                    Role_Description__c,
                                    Role_Functionalknowledge__c,
                                    Role_Technicalknowledge__c,
                                    Role_MentoringRequiered__c,
                                    Role_Communication__c,
                                    Role_Prerequisites__c,
                                    Role_Softskills__c  
                                FROM Salesforce_Career_Path_Settings__mdt WHERE Label =: getRole(empId)];
        if (!lstroleDesc.isEmpty()) {
            roleDesc = lstroleDesc[0];
        }
        return roleDesc;
    } 

    public static String getRole(String empId){
        string strCurrentRole = '';
        String currentRoleString = '';
        List<Salesforce_Career_Path_Settings__mdt> lstCareerPathSettings = new List<Salesforce_Career_Path_Settings__mdt>();

        List<Contact> lstContact = [SELECT Id, Name, Role__c 
                                    FROM Contact 
                                    WHERE Id =: empId];
        if(!Test.isRunningTest()) {
             lstCareerPathSettings = [SELECT Id, MasterLabel, Position__c
                                        FROM Salesforce_Career_Path_Settings__mdt
                                        ORDER BY Position__c];
        }
        else {
            Salesforce_Career_Path_Settings__mdt mdtCareerPath1 = new Salesforce_Career_Path_Settings__mdt();
            mdtCareerPath1.MasterLabel = 'Trainee';
            mdtCareerPath1.Position__c = 11;
            mdtCareerPath1.Role_Softskills__c = 'Comunicación escrita y oral, con equipo';
            lstCareerPathSettings.add(mdtCareerPath1);

            Salesforce_Career_Path_Settings__mdt mdtCareerPath2 = new Salesforce_Career_Path_Settings__mdt();
            mdtCareerPath2.MasterLabel = 'Developer';
            mdtCareerPath2.Position__c = 12;
            mdtCareerPath2.Role_Softskills__c = 'Comunicación escrita y oral, con equipo';
            lstCareerPathSettings.add(mdtCareerPath2);
        }
        
        if (lstContact != null) {
            strCurrentRole = lstContact[0].Role__c;
        }

        if (!lstCareerPathSettings.isEmpty()) {
            for (Salesforce_Career_Path_Settings__mdt objCareerPath : lstCareerPathSettings) {
                String strRoleSalesforce = 'Salesforce ' + objCareerPath.MasterLabel;
                    if(strRoleSalesforce == strCurrentRole){
                        currentRoleString =  objCareerPath.MasterLabel;
                    }        
                }
            }
        return currentRoleString;
    }
}